bcgov/GDX-Analytics-Looker-Snowplow-Web-Block

- page_views.view.lkml
- sessions_rollup.view.lkml
- snowplow_web_block.model.lkml
changed page_View_index to page_view_in_session_index to allow id of landing and exit pages
> added lookml changes for dahsboard

- sessions.view.lkml
Changes from co-dev session with Hugo resulting from GDXDSD-1209.
> Updates to sessions dates and date range calculations

- cmslite_themes.view.lkml
- snowplow_web_block.model.lkml
Hey @mark-walle can you review? 
This is to connect with dashboards/57
> added initial version of theme and subtheme code

- sessions.view.lkml
GDXDSD-1203
Explore: https://analytics.gov.bc.ca/explore/snowplow_web_block/sessions?qid=018k6eSM3lBdIuhG4EFIg6&toggle=vis
> comparison_date overlays current period data with last period data

- sessions.view.lkml
- web_analytics.dashboard.lookml
GDXDSD-1263 normalizing on common dimension names for common functions across projects.
> session_start_window replaced with date_window

- page_views.view.lkml
- sessions.view.lkml
Also updated in wiki and Content Validator.
> is_in_range replaced with is_in_current_period_and_last_period

- snowplow_web_block.model.lkml
I have added the cms lite theme and sub-theme meta data to the clicks explore.
> GDXDSD-1277-added the theme meta data to the clicks table

- page_views.view.lkml
- sessions.view.lkml
In both sessions and page_views
> conditional operators matched on current_period and last_period

- sessions.view.lkml
> Documentation and description parameters on fields in sessions.view.

- users.view.lkml
> end sql statement on dimension network_userid to fix file.

- clicks.view.lkml
> added slider_clicks yesno field to clicks which finds pull-left elements

- page_views.view.lkml
- sessions.view.lkml
@mark-walle To your point earlier, does this change to the documentation clarify things?
It's worth including this so there's no confusion later.
> explanation of DATEDIFF(SECOND usage

- shared_fields_common.view.lkml
Hey @mark-walle : How does this look as a solution to the "Victoria, Texas" problem. 
I've left City as a dimension as well, but this one should do us better, I think, as a filter.
> add city_and_region field

- page_views.view.lkml
- sessions.view.lkml
- snowplow_web_block.model.lkml
Changed the view files for sessions and page_views to use Pacific Time natively. 
Also made a new Looker Connection that assumes Pacific Time to avoid timezone conversions.
> move to natively use pacific time

- clicks.view.lkml
- shared_fields_common.view.lkml
Hey @mark-walle : Here's the change I showed you this afternoon.
> updating dimensions to support linking

- cmslite_themes.view.lkml
- cmslite_themes_cache.view.lkml
- snowplow_web_block.model.lkml
To persist fields on theme and subtheme until cmsl microservice has inserted new cmsl metadata.
> derived tables for theme and subtheme suggestions

- README.md
@danpollock Can you please review?
> Cleaning - Farhood Looker Snowplow Web Block

- date_comparisons_common.view.lkml
Fixes to date range calculations to better support "date before" and "any date"
> date range bug fixes

- city_cache.view.lkml
- shared_fields_common.view.lkml
- snowplow_web_block.model.lkml
Tested to work by sudoing as different and switching their dev branch to the dev-mark-walle-rqwn branch on commit https://github.com/bcgov/GDX-Analytics-Looker-Snowplow-Web-Block/commit/a974656b4291f0bc646fa13a154af83383b6402f.
> City filter suggestion cache using daily triggered PDT

- sessions.view.lkml
- shared_fields_common.view.lkml
- site_cache.view.lkml
- snowplow_web_block.model.lkml
Suggested values on the site field are tested and seen to work when pulling this branch into dev and switching between users on that branch, testing the filter field in various dashboards.
> Site filter cache from sessions first_page_urlhost

- gdx_analytics_whitelist.view.lkml
- page_views.view.lkml
- snowplow_web_block.model.lkml
@danpollock can you please review?
> new view and explore changes to join page view url host to the whitelist

- page_views.view.lkml
- sessions.view.lkml
- shared_fields_common.view.lkml
- snowplow_web_block.model.lkml
A simple change. I've tested it. Seeking a quick review as a sanity check.
> updating filters to remove campaign_urlhost and add exclusion_filter

- shared_fields_common.view.lkml
Hey @mark-walle , can I get a quick review on this new Dimension?
> add geo_bc

- cmslite_metadata.view.lkml
Ive updated the dimension labels and descriptions for the metadata language columns.
> Updates to metadata languages lookml

- Views/searches.view.lkml
Ive added the search v2 dimension using the logic that will eventually go in the batch pipeline.
> Added search_terms_v2 dimension.

- Dashboards/gov1.dashboard.lookml
- Models/snowplow_web_block.model.lkml
- Views/cmslite_metadata.view.lkml
- Views/cmslite_themes.view.lkml
- Views/cmslite_themes_cache.view.lkml
- manifest.lkml
- snowplow_web_block.model.lkml
Changed to use cmslite metadata as an imported project.
> Import cmslite_metadata project

- Views/clicks.view.lkml
Ive updated target_display_url. I also added target_urlscheme as it was needed for target_display_url.
> Updated logic for target_display_url, added target_urlscheme.

- Views/cmslite_metadata.view.lkml
- Views/cmslite_themes.view.lkml
- manifest.lkml
Updated cmslite_metadata derived table to only pull required dimensions.
Included and extended cmslite themes view.
Added project manifest file to enable includes.
> Dev brendan jennings pxtd

- snowplow_web_block.model.lkml
@BJenning can you please review this addition of a datagroup to the model file.
> Midnight datagroup to use as materializtion trigger for AA tables

- Includes/shared_fields_common.view.lkml
- Views/chatbot.view.lkml
Reverts bcgov/GDX-Analytics-Looker-Snowplow-Web-Block#257
> Revert "reverting chip click on big chatbot PDT as it seems to have increased…"

- README.md
> Lifecycle badge updated

- Views/chatbot.view.lkml
- Views/chatbot_intents_and_clicks.view.lkml
- Views/cit_userstory.view.lkml
PDT fix for chatbot (and a minor typo fix for CIT).
> PDT fix for chatbot (GDXDSD-5122)

- snowplow_web_block.model.lkml
Reverts bcgov/GDX-Analytics-Looker-Snowplow-Web-Block#334
> Revert "Temporary fix to disable incremental PDT triggers (GDXDSD-5180)"
